version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Starting build process with stage $BUILD_ENV
      - ng build
      - ng e2e
  post_build:
    commands:
      - echo Build real2 completed on `date`
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
  base-directory: dist/test-worked
